v0.90.0

diff --git a/bin/release b/bin/release
--- a/bin/release
+++ b/bin/release
@@ -1,6 +1,13 @@
+MSG="$1"
+
+if [ -z "$MSG" ]; then
+echo "Error: Missing commit message."
+exit 1
+fi
+
 git add -A .
-git commit -m "$1"
-git tag "$1"
+git commit -m "$MSG"
+git tag "$MSG"
 git push
 git push --tags
 
